
make:
	python3 collage.py
#	python3 analysis_02.py
#	python3 analysis_03.py
#	python3 analysis_04.py
#	python3 analysis_05.py
	python3 analysis_06.py


clean:
	cls
	del /q "C:\Users\hoste\Desktop\Programming\12_Taipeh_Drop_Motion\Plots\*"
	del /q "C:\Users\hoste\Desktop\Programming\12_Taipeh_Drop_Motion\Collages\*"